language: cpp
dist: focal

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['g++-multilib', 'valgrind', 'expect', 'curl', 'libopenblas-dev']
      env:
        - COMPILER=g++
        - COMP=gcc

#    - os: linux
#      compiler: clang
#      addons:
#        apt:
#          packages: ['clang-10', 'llvm-10-dev', 'g++-multilib', 'valgrind', 'expect', 'curl', 'openblas']
#      env:
#        - COMPILER=clang++-10
#        - COMP=clang
#
#    - os: osx
#      osx_image: xcode12
#      compiler: gcc
#      env:
#        - COMPILER=g++
#        - COMP=gcc
#
#    - os: osx
#      osx_image: xcode12
#      compiler: clang
#      env:
#        - COMPILER=clang++
#        - COMP=clang

branches:
  only:
   - master

before_script:
  - cd src

script:
  # Download net
  - make net

  # Obtain bench reference from git log
  - git log HEAD | grep "\b[Bb]ench[ :]\+[0-9]\{7\}" | head -n 1 | sed "s/[^0-9]*\([0-9]*\).*/\1/g" > git_sig
  - export benchref=$(cat git_sig)
  - echo "Reference bench:" $benchref

  # Compiler version string
  - $COMPILER -v

  # test help target
  - make help

  #
  # Valgrind
  #
  - export CXXFLAGS="-O1 -fno-inline"
  - make clean && make -j2 ARCH=x86-64-modern debug=yes optimize=no build > /dev/null && ../tests/instrumented.sh --valgrind
  - ../tests/instrumented.sh --valgrind-thread
